on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target_type:
          - server
          - client
    steps:
      - uses: actions/checkout@v6

      - uses: xmake-io/github-action-setup-xmake@v1

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache xmake
        uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
            build
          key: xmake-${{ runner.os }}-levilamina-v1

      - run: xmake repo -u

      - run: xmake f -a x64 -m release -p windows --target_type=${{ matrix.target_type }} -y

      - run: xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}-${{ matrix.target_type }}-windows-x64
          path: bin/
